### PR TITLE
Applied SUPEE-10570 v2

### PR DESCRIPTION
**Pull request by SnowCommerceBrand**
Applied Patch to 1.9.3.8 Branch and added v1.9.3.8-patch1 tag

This Patch fixes Session Issues In Cart and Checkout

### CODE REVIEW

**Comment by internalsystemerror** [comment]
Yes please!

**Comment by internalsystemerror** [comment]
@danslo can you help? eager to get this.

**Comment by danslo** [comment]
Not sure how I missed the notification on this, but merged!

**Comment by danslo** [comment]
And tagged now as well.

**Comment by internalsystemerror** [comment]
ty

**Pull request merged**
