### PR TITLE
V1.9.3.6

### PR DESCRIPTION
**Pull request by muhkuh2005**

### CODE REVIEW

**Comment by danslo** [comment]
I've separately pushed it in branch magento-1.9.3.6 and drafted a new release instead of merging this into magento-1.9.3.4. Thanks for your contribution!

**Comment by muhkuh2005** [comment]
That was my intention, but I cannot create new branches in this repo :)

**Comment by danslo** [comment]
:+1: Thanks again!

**Comment by muhkuh2005** [comment]
Would it have been better to push it into the master then?
It looks like all the GIT-reference is now lost with your method.
As far as I remember the other mods had created a new branch with the pullrequest acceptance.
See #59

**Comment by danslo** [comment]
I probably looked over the fact that you can do this in the github interface, so it's probably my mistake.

Just did a simple:

```bash
git fetch firegento pull/71/head:magento-1.9.3.6
git checkout magento-1.9.3.6
git push -u firegento magento-1.9.3.6
```

Maybe we can test this theory at 1.9.3.7 :man_shrugging:

**Pull request closed without merging**
