### PR TITLE
Magento 1.9.2.4 SUPEE-8788 patch

### LINKED ISSUE #39: SUPEE-8788
The latest Magento 1 security patch SUPEE-8788 contains 17 APPSEC updates...https://goo.gl/ZLtHB3

### PR DESCRIPTION
**Pull request by reillo**
fixes #39

### CODE REVIEW

**Comment by razbakov** [comment]
@reillo  thank you!

**Comment by infabo** [comment]
@razbakov how could you accept this PR without checking? This PR is bullshit (sry) as bullshit can get. Sry to be so rude, but firegento should remain a trusted source IMHO!

The whole new Mage Uploader extension is missing, Mage_Centinel Api Client removed, no applied patches list and so on. it is totally broken. 👎

**Comment by razbakov** [comment]
@infabo thank you for information, i reverted PR.
I will push tomorrow magento 1.9.3. 
I think it would be better than introduce a new patch version, as it should be the same as 1.9.3 version.

**Comment by razbakov** [comment]
@infabo i can't find official download link for magento 1.9.3. did you find one?

**Pull request merged**
