### PR TITLE
v1.9.3.7

### PR DESCRIPTION
**Pull request by toobaer**
v1.9.3.7

### CODE REVIEW

**Comment by danslo** [comment]
Branched from 1.9.3.6, then applied diff:
https://github.com/firegento/magento/tree/magento-1.9.3.7

I've tagged a new release.

**Comment by muhkuh2005** [comment]
Can someone please brief danslo how to accept pull requests?
I am glad there is some quick response, but this is the second time some pull request didn't work out correctly...

**Comment by danslo** [comment]
I know how to accept pull requests. I won't merge a pull request with such a history.

edit: That is to say, I don't want to clobber up the 1.9.3.7 branch with a bunch of merge commits when we can have a clean history with applied patch.

**Comment by danslo** [comment]
@muhkuh2005 I just realized you were probably talking about attribution... Fair point. I've pulled the appropriate commit from this PR and updated the branch.

**Comment by muhkuh2005** [comment]
Yeah sorry, I have been noted by a workmate that my comment looked pretty offensive; that wasn't my intention.

Beside the attribution it seems to be the SUPEE-10415 applied to v1.9.3.6 instead of an full upgrade package.
Therefore this should not be called v1.9.3.7 but v1.9.3.6-patch1.

May someone please verify that? I am a little dorked today.

**Comment by danslo** [comment]
I didn't take it in such a way, no worries. And yes I also noticed that afterwards, some files in ``var`` were unaffected. Give me an hour or two and I'll try to correct it.

**Comment by danslo** [comment]
Alright, so I think it's fixed now. 1.9.3.7 is 1.9.3.6 branch with diff applied to upgrade.

1.9.3.6 got applied patch and tagged as 1.9.3.6-patch1.

**Pull request closed without merging**
