### PR TITLE
Fixed reorder isSalable check function

### PR DESCRIPTION
**Pull request by sunel**
Due to the wrong code indentation. The for loop is wrongly closed.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
Thank you for your contribution. But this repository only accepts official patches from Magento.

Please provide an official patch and we will apply it :-)

**Comment by razbakov** [comment]
@sunel did you already send your patch to magento?

**Comment by sunel** [comment]
@razbakov  already this bug has been reported 4 months back, but still no patch is avaliable

**Comment by razbakov** [comment]
@sunel I suggest to commit all non-official patches to https://github.com/kirchbergerknorr/magento-patches and organise it like magento module (installable via composer and modman). Can you please submit your changed file there? I will pack it with composer/modman/readme ASAP.

@SchumacherFM do you have permission to move this repo to firegento?

**Comment by sunel** [comment]
@razbakov  seems like a empty repo , do i need to push the files that are changed  to this repo or ??? can you guide me on this ...

**Comment by razbakov** [comment]
@sunel yes, can you just push the file `app/code/core/Mage/Sales/Model/Order.php` to repo saving the folder-structure?

**Comment by razbakov** [comment]
@sunel and please write comments around code, you have changed:

```
// start patch
your changed code
// end patch
```

**Comment by sunel** [comment]
Sure will do it , but as the repo is empty iam unable to fork or even clone it

**Comment by razbakov** [comment]
@sunel I added file, try now

**Comment by sunel** [comment]
@razbakov  just created a pull request to the repo u mentioned

**Pull request closed without merging**
