### PR TITLE
v1.9.3.4

### PR DESCRIPTION
**Pull request by ramsaybell**
Full M1 CE 1.9.3.4 from the following file:
`magento-1.9.3.4-2017-07-12-04-19-23.tar.gz`

M1 CE 1.9.3.4 includes this patch:
`SUPEE-9767 v2`

Further information on the update:
https://magento.stackexchange.com/questions/176871/security-patch-supee-9767-possible-issues

### CODE REVIEW

**Comment by wytzejan** [comment]
Can someone with permission create the tag magento-1.9.3.4 and place this pull request in this tag?
Thanks!

**Comment by razbakov** [comment]
@mautz-et-tong you merged it to the wrong branch

**Comment by mautz-et-tong** [comment]
Will fix it

**Comment by razbakov** [comment]
I reverted the commit

**Comment by mautz-et-tong** [comment]
Thx

**Pull request merged**
